export const websitePackages = [
  {
    id: "starter-web-page",
    slug: "starter-web-page",
    name: "Starter Web Page",
    shortName: "Starter",
    category: "Website Foundation",
    startingPrice: 395,
    priceLabel: "Starting at $395",
    pageCount: "1 page",
    bestForLabel: "Best for a simple professional web presence",
    heroHeadline:
      "A focused one-page web presence built to make your business look professional.",
    shortDescription:
      "A streamlined one-page website for businesses that need a clean, credible place to send customers online.",
    fullDescription:
      "The Starter Web Page is designed for businesses that need a professional online presence without jumping into a full multi-page website. It gives customers a clear place to learn who you are, what you offer, where you serve, and how to contact you.",
    primaryGoal:
      "Get online with a professional, mobile-friendly web presence.",
    businessStage:
      "New businesses, referral-based businesses, solo service providers, or companies that need a simple starting point.",
    customerIntent:
      "The customer needs a clean online presence, not a deep SEO strategy or advanced website system yet.",
    includedPages: [
      "One custom landing page",
      "Business overview section",
      "Services or offerings section",
      "Contact section",
      "Service area or location section",
    ],
    includedFeatures: [
      "Mobile-friendly page layout",
      "Professional page structure",
      "Click-to-call phone link",
      "Email/contact button",
      "Map or service-area section when applicable",
      "Social media links",
      "Basic SEO title and meta description",
      "Basic image optimization",
      "One structured revision round",
    ],
    notIncluded: [
      "Multiple website pages",
      "Dedicated SEO service pages",
      "Advanced quote forms",
      "Online payments or checkout",
      "Customer logins or portals",
      "Employee dashboards",
      "Custom automation systems",
      "Ongoing SEO content strategy",
    ],
    goodFitExamples: [
      "A new business that needs something professional to show customers",
      "A service provider who gets most work from referrals",
      "A small local or regional business that needs a simple contact page",
      "A business owner who wants to start lean and upgrade later",
    ],
    upgradeTriggers: [
      "The business needs multiple pages",
      "The website needs dedicated pages for each service",
      "The business wants stronger SEO structure",
      "The site needs advanced forms, payments, booking, or business tools",
    ],
    timeline: "Estimated 1 week after required content is received",
    revisionRounds: 1,
    primaryCta: "Build My Starter Web Page",
    secondaryCta: "Compare Website Options",
    paymentOptions: {
      payInFull: {
        label: "Pay in full",
        amountDueToday: 395,
        total: 395,
        note: "Best for the fastest start and simplest project terms.",
      },
      deposit: {
        label: "Deposit plan",
        amountDueToday: 195,
        remainingBalance: 200,
        total: 395,
        note: "Remaining balance is due before launch.",
      },
      monthly: {
        label: "Starter monthly plan",
        amountDueToday: 150,
        monthlyPayment: 49,
        termMonths: 6,
        estimatedTotal: 444,
        note: "Website remains under Hullinger Digital management until the agreement is paid in full.",
      },
    },
    carePlanEligibility: ["essential-care"],
    recommendedAddOnCategories: [
      "Design & Media",
      "Basic Forms",
      "Local Visibility",
    ],
  },

  {
    id: "launch-website",
    slug: "launch-website",
    name: "Launch Website",
    shortName: "Launch",
    category: "Custom Informational Website",
    startingPrice: 1295,
    priceLabel: "Starting at $1,295",
    pageCount: "1–3 pages",
    bestForLabel: "Best for a custom informational website",
    heroHeadline: "A custom informational website built around your business.",
    shortDescription:
      "A professional custom website for businesses that need more room to explain who they are, what they do, and how customers can get started.",
    fullDescription:
      "The Launch Website is built for businesses that need a stronger online home than a one-page site. It gives your business a polished structure, clear messaging, service information, and a professional contact path without moving into a full lead-generation or advanced website build.",
    primaryGoal:
      "Create a professional multi-page website that builds credibility and makes the business easier to understand.",
    businessStage:
      "Businesses that need a credible online home, clearer service information, and a stronger first impression.",
    customerIntent:
      "The customer needs a custom informational website, but does not yet need deep SEO service pages or advanced business functionality.",
    includedPages: [
      "Custom homepage",
      "About or company section/page",
      "Services overview page or section",
      "Contact page or contact section",
      "Up to 3 total pages",
    ],
    includedFeatures: [
      "Custom page structure",
      "Professional design direction",
      "Mobile-friendly responsive layout",
      "Basic brand polish",
      "Basic SEO setup for included pages",
      "Image optimization",
      "Clear calls to action",
      "Contact form or contact section",
      "Two structured revision rounds",
    ],
    notIncluded: [
      "Dedicated SEO pages for every service",
      "Large service-area SEO structure",
      "Advanced quote forms",
      "Online checkout or payments",
      "Customer accounts or portals",
      "Employee/internal dashboards",
      "Advanced automations",
      "Ongoing SEO campaign work",
    ],
    goodFitExamples: [
      "A business that needs a more credible website than a single page",
      "A company with a few core services to explain",
      "A business that wants a polished online presence before investing in SEO growth",
      "A professional service provider that needs trust and clarity",
    ],
    upgradeTriggers: [
      "The business wants to rank for multiple services",
      "The site needs 5 or more pages",
      "The customer journey needs stronger lead capture",
      "The business wants dedicated landing pages, FAQs, testimonials, or service-area content",
      "The site needs tools like payments, booking, portals, dashboards, or automations",
    ],
    timeline: "Estimated 1–2 weeks after required content is received",
    revisionRounds: 2,
    primaryCta: "Build My Launch Website",
    secondaryCta: "Compare Website Options",
    paymentOptions: {
      payInFull: {
        label: "Pay in full",
        amountDueToday: 1165,
        total: 1165,
        discountApplied: 130,
        note: "Includes a 10% pay-in-full discount.",
      },
      deposit: {
        label: "Deposit plan",
        amountDueToday: 650,
        remainingBalance: 645,
        total: 1295,
        note: "Remaining balance is due before launch.",
      },
      monthly: {
        label: "Launch monthly plan",
        amountDueToday: 395,
        monthlyPayment: 149,
        termMonths: 8,
        estimatedTotal: 1587,
        note: "Website remains under Hullinger Digital management until the agreement is paid in full.",
      },
    },
    carePlanEligibility: ["essential-care", "professional-care"],
    recommendedAddOnCategories: [
      "Pages & Content",
      "Design & Media",
      "Basic SEO",
      "Forms & Lead Capture",
    ],
  },

  {
    id: "lead-generating-website",
    slug: "lead-generating-website",
    name: "Lead-Generating Website",
    shortName: "Lead-Generating",
    category: "SEO & Lead-Focused Website",
    startingPrice: 3950,
    priceLabel: "Starting at $3,950",
    pageCount: "5–10 pages",
    bestForLabel: "Best for service businesses that want more qualified inquiries",
    heroHeadline:
      "A custom website built to get found, build trust, and turn visitors into leads.",
    shortDescription:
      "A stronger custom website built around SEO structure, service pages, trust-building content, and better customer inquiry flow.",
    fullDescription:
      "The Lead-Generating Website is designed for businesses that need more than a professional online presence. It is built around search visibility, dedicated service content, customer trust, and a clear path from visitor to inquiry.",
    primaryGoal:
      "Build a website that supports visibility, credibility, and lead generation.",
    businessStage:
      "Growing businesses, service companies, and established operators that want their website to become a stronger sales and lead-generation asset.",
    customerIntent:
      "The customer wants a website that can help them get found, educate visitors, build trust, and produce better inquiries.",
    includedPages: [
      "Custom homepage",
      "About or company page",
      "Dedicated service pages",
      "Contact or quote request page",
      "FAQ section or page",
      "Reviews/testimonials section",
      "Up to 10 total pages",
    ],
    includedFeatures: [
      "SEO-focused page structure",
      "Dedicated service-page strategy",
      "Lead-focused calls to action",
      "Quote/contact form",
      "Trust-building content sections",
      "FAQ structure",
      "Review/testimonial section",
      "Service-area content structure",
      "Basic analytics setup",
      "Basic conversion flow planning",
      "Mobile-friendly responsive layout",
      "Three structured revision rounds",
    ],
    notIncluded: [
      "Large custom software systems",
      "Customer account portals",
      "Employee dashboards",
      "Complex workflow tracking",
      "Advanced AI tools",
      "Full e-commerce systems",
      "Ongoing SEO content publishing unless selected separately",
    ],
    goodFitExamples: [
      "A contractor or service business that wants better quote requests",
      "A company that needs individual pages for each major service",
      "A business that wants stronger Google visibility over time",
      "A business that needs to explain value, process, reviews, and FAQs before customers call",
    ],
    upgradeTriggers: [
      "The website needs customer logins",
      "The business needs internal staff tools",
      "The website needs online ordering, payments, approvals, or dashboards",
      "The project requires custom database-driven workflows",
      "The site needs AI-assisted intake, estimating, replies, or summaries",
    ],
    timeline: "Estimated 3–5 weeks after required content is received",
    revisionRounds: 3,
    primaryCta: "Build My Lead-Generating Website",
    secondaryCta: "Explore Advanced Website Tools",
    paymentOptions: {
      payInFull: {
        label: "Pay in full",
        amountDueToday: 3555,
        total: 3555,
        discountApplied: 395,
        note: "Includes a 10% pay-in-full discount.",
      },
      deposit: {
        label: "Milestone plan",
        amountDueToday: 1500,
        midpointPayment: 1225,
        finalPayment: 1225,
        total: 3950,
        note: "Midpoint and final balances are due according to the project agreement.",
      },
      monthly: {
        label: "Growth monthly plan",
        amountDueToday: 995,
        monthlyPayment: 349,
        termMonths: 12,
        estimatedTotal: 5183,
        note: "Website remains under Hullinger Digital management until the agreement is paid in full.",
      },
    },
    carePlanEligibility: ["professional-care", "growth-care"],
    recommendedAddOnCategories: [
      "Pages & Content",
      "SEO & Local Visibility",
      "Forms & Lead Capture",
      "Automations",
      "Booking & Scheduling",
    ],
  },

  {
    id: "advanced-website",
    slug: "advanced-website",
    name: "Advanced Website",
    shortName: "Advanced",
    category: "Website With Business Tools",
    startingPrice: 8500,
    priceLabel: "Starting at $8,500",
    pageCount: "Custom scope",
    bestForLabel: "Best for websites that need built-in tools or workflows",
    heroHeadline: "A custom website with business tools built in.",
    shortDescription:
      "A custom website for businesses that need more than pages — including portals, dashboards, workflows, automations, payments, e-commerce, or AI-assisted tools.",
    fullDescription:
      "The Advanced Website is built for businesses that need the website to support real operations. The public website can act as the front door, while private tools such as customer portals, employee dashboards, quote systems, file uploads, approvals, payments, workflows, and AI assistants can support the work behind the scenes.",
    primaryGoal:
      "Create a custom website that combines marketing, lead flow, and business functionality.",
    businessStage:
      "Serious small businesses, growing companies, and established operators that need the website to do more than present information.",
    customerIntent:
      "The customer needs custom functionality, not just standard website pages.",
    includedPages: [
      "Custom homepage",
      "Core service or business pages",
      "Contact or request page",
      "Advanced feature planning",
      "Up to 10 standard website pages before add-ons or custom scope expansion",
    ],
    includedFeatures: [
      "Advanced project planning",
      "Custom feature mapping",
      "Expanded form logic",
      "One advanced feature module up to $1,500 value",
      "Admin-ready structure",
      "Basic database or workflow planning when needed",
      "Lead-generation structure",
      "SEO-conscious page planning",
      "Mobile-friendly responsive layout",
      "Four structured revision rounds",
    ],
    possibleAdvancedFeatures: [
      "Customer account login",
      "Employee or staff login",
      "Customer dashboard",
      "Employee dashboard",
      "Quote request system",
      "Photo or file upload system",
      "Estimate approval flow",
      "Scheduling or appointment request workflow",
      "Payment or deposit collection",
      "Product or service checkout",
      "Order status or job status view",
      "Lead tracking",
      "Job or workflow tracking",
      "Internal notes",
      "Admin panel",
      "Automated email or SMS notifications",
      "AI intake summaries",
      "AI reply assistant",
      "AI estimate helper",
      "Reporting dashboard",
    ],
    notIncluded: [
      "Unlimited custom features",
      "Unlimited revisions",
      "Enterprise software development beyond the agreed scope",
      "Third-party platform fees",
      "Payment processor fees",
      "Ongoing support unless a care plan is selected",
    ],
    goodFitExamples: [
      "A business that wants customers to log in and submit requests",
      "A company that needs employees to manage leads, jobs, or approvals",
      "A business that wants quote requests, uploads, payments, and status updates organized online",
      "A company that wants AI-assisted intake, replies, summaries, or estimating support",
      "A business that wants its website to function like a lightweight operations system",
    ],
    upgradeTriggers: [
      "Custom feature scope exceeds the included advanced module",
      "The project requires multiple dashboards, roles, or database-driven workflows",
      "The project becomes a custom software platform rather than a website with tools",
      "The business needs ongoing development after launch",
    ],
    timeline: "Estimated 6–10+ weeks depending on approved scope and features",
    revisionRounds: 4,
    primaryCta: "Build My Advanced Website",
    secondaryCta: "Request Advanced Project Review",
    paymentOptions: {
      payInFull: {
        label: "Pay in full",
        amountDueToday: 7650,
        total: 7650,
        discountApplied: 850,
        note: "Includes a 10% pay-in-full discount.",
      },
      milestone: {
        label: "Milestone plan",
        amountDueToday: 2500,
        total: 8500,
        note: "Remaining payments are divided by approved project milestones before launch.",
      },
      monthly12: {
        label: "Advanced 12-month plan",
        amountDueToday: 2000,
        monthlyPayment: 699,
        termMonths: 12,
        estimatedTotal: 10388,
        note: "Website remains under Hullinger Digital management until the agreement is paid in full.",
      },
      monthly18: {
        label: "Advanced 18-month plan",
        amountDueToday: 1500,
        monthlyPayment: 499,
        termMonths: 18,
        estimatedTotal: 10482,
        note: "Website remains under Hullinger Digital management until the agreement is paid in full.",
      },
    },
    carePlanEligibility: ["advanced-care"],
    recommendedAddOnCategories: [
      "Customer Tools",
      "Employee/Internal Tools",
      "Online Sales & Payments",
      "Automations",
      "AI Tools",
      "Advanced Forms",
    ],
  },
];

export const packageComparisonNotes = {
  starter:
    "Starter is for getting online with a focused one-page presence. It is intentionally simple and does not replace a full website strategy.",
  launch:
    "Launch is for businesses that need a professional multi-page website, but not a deep SEO or lead-generation build yet.",
  leadGenerating:
    "Lead-Generating is for businesses that want their website structured around visibility, trust, service pages, and better inquiries.",
  advanced:
    "Advanced is for businesses that need the website to include tools, workflows, portals, dashboards, payments, automations, or AI-assisted features.",
};

export const packageUpgradeRule =
  "A client does not move up packages because of one small extra request. They move up when the website needs a different level of strategy, SEO depth, lead generation, or built-in business functionality.";

export const packageReviewNotice =
  "All website orders are reviewed by Hullinger Digital before production begins. If the submitted project details include requirements that are unclear, technically incompatible, impossible to complete as selected, or outside the purchased package or add-ons, Hullinger Digital will contact the client to review available options. This may include adjusting the scope, adding approved services, upgrading the package, revising the timeline, or canceling/refunding according to the agreement terms.";